// Seals the game page into the launcher: strips the developer console hooks,
// gzips it, encrypts it with a fresh AES-256 key, and writes the key into the
// launcher split in two halves.
// Copyright (c) 2026 NIKJYAR Studios. All rights reserved.
package main

import (
	"bytes"
	"compress/gzip"
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"fmt"
	"os"
	"strings"
)

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: seal <game.html> <launcher dir>")
		os.Exit(2)
	}
	src, err := os.ReadFile(os.Args[1])
	must(err)
	html := string(src)
	// the debug console object (teleport, give items, skip beats) stays out of the release
	if i := strings.LastIndex(html, "window.IGMC={"); i >= 0 {
		j := strings.Index(html[i:], "\nboot();")
		if j < 0 {
			fail("could not find the end of the debug export")
		}
		html = html[:i] + html[i+j+1:]
	}
	if !strings.Contains(html, "boot();") || !strings.Contains(html, "NIKJYAR Studios") {
		fail("the page does not look like the game")
	}
	var gz bytes.Buffer
	zw, _ := gzip.NewWriterLevel(&gz, gzip.BestCompression)
	zw.Write([]byte(html))
	zw.Close()

	key := make([]byte, 32)
	mask := make([]byte, 32)
	nonce := make([]byte, 12)
	for _, b := range [][]byte{key, mask, nonce} {
		_, err := rand.Read(b)
		must(err)
	}
	block, err := aes.NewCipher(key)
	must(err)
	gcm, err := cipher.NewGCM(block)
	must(err)
	out := gcm.Seal(append([]byte{}, nonce...), nonce, gz.Bytes(), []byte("NIKJYAR Studios · IGMC Night Watch"))
	dir := os.Args[2]
	must(os.WriteFile(dir+"/game.bin", out, 0o644))

	a := make([]byte, 32)
	for i := range key {
		a[i] = key[i] ^ mask[(i*7)%32]
	}
	var g strings.Builder
	g.WriteString("// Code generated by seal. DO NOT EDIT.\n\npackage main\n\n")
	g.WriteString("var kA = [32]byte{" + list(a) + "}\n")
	g.WriteString("var kB = [32]byte{" + list(mask) + "}\n\n")
	g.WriteString("func sealKey() []byte {\n\tk := make([]byte, 32)\n\tfor i := range k {\n\t\tk[i] = kA[i] ^ kB[(i*7)%32]\n\t}\n\treturn k\n}\n")
	must(os.WriteFile(dir+"/key_gen.go", []byte(g.String()), 0o644))
	fmt.Printf("sealed %d bytes of page into %d bytes\n", len(html), len(out))
}

func list(b []byte) string {
	s := make([]string, len(b))
	for i, v := range b {
		s[i] = fmt.Sprintf("0x%02x", v)
	}
	return strings.Join(s, ",")
}

func must(err error) {
	if err != nil {
		fail(err.Error())
	}
}

func fail(m string) { fmt.Fprintln(os.Stderr, "seal:", m); os.Exit(1) }
